apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: cinematrix
  labels:
    app: webapp
type: Opaque
stringData:
  connection-string: "Server=sqlserver-service;Database=MoviePlatformDb;User Id=sa;Password=CineMatrix2026!;TrustServerCertificate=True;MultipleActiveResultSets=true"
  tmdb-api-key: "8fb06c7cadbf317c40320746d7d2d9cf"