apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: cinematrix
  labels:
    app: webapp
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: ClientIP